/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/
import React from 'react';
import ReactDOM from 'react-dom/client';

// --- Components ---

const Header = () => (
  <header className="bg-white/80 backdrop-blur-md shadow-md sticky top-0 z-50">
    <nav className="container mx-auto px-6 py-4 flex justify-between items-center">
      <div className="text-2xl font-bold text-gray-800">
        Pavillion Medical
      </div>
      <a
        href="http://calendar.app.google/NSVqrYKdL8SCCtem8"
        target="_blank"
        rel="noopener noreferrer"
        className="bg-pink-500 hover:bg-pink-600 text-white font-bold py-2 px-4 rounded-full transition duration-300 ease-in-out transform hover:scale-105"
        aria-label="Book an appointment"
      >
        Book Now
      </a>
    </nav>
  </header>
);

const Hero = () => (
  <section className="bg-white py-20">
    <div className="container mx-auto px-6 text-center">
      <h1 className="text-5xl font-extrabold text-gray-900 mb-4 leading-tight">
        Refresh Your Look with Botox
      </h1>
      <p className="text-2xl text-gray-600 mb-8">
        Safe, effective, and only <span className="font-bold text-pink-600">$8 per unit</span>.
      </p>
      <a
        href="http://calendar.app.google/NSVqrYKdL8SCCtem8"
        target="_blank"
        rel="noopener noreferrer"
        className="bg-pink-500 hover:bg-pink-600 text-white font-bold py-4 px-8 rounded-full text-lg transition duration-300 ease-in-out transform hover:scale-105 inline-block"
      >
        Schedule Your Appointment
      </a>
      <div className="mt-12 flex justify-center">
        {/*
          This image would be generated by Nano Banana ('gemini-2.5-flash-image-preview') with a prompt like:
          "A friendly, cartoon-style illustration of a diverse group of happy people with smooth, glowing skin, in a clean, modern medical spa setting. A doctor in a lab coat is smiling in the background. Soft pastel colors."
        */}
        <img
          src="https://picsum.photos/seed/pavillion-hero/1000/400"
          alt="Happy clients at Pavillion Medical"
          className="rounded-lg shadow-xl w-full max-w-4xl h-auto object-cover"
        />
      </div>
    </div>
  </section>
);

const About = () => (
    <section id="about" className="py-16 bg-slate-50">
        <div className="container mx-auto px-6">
            <div className="text-center mb-12">
                <h2 className="text-4xl font-bold text-gray-800">What is Botox?</h2>
                <p className="text-gray-600 mt-4 max-w-2xl mx-auto">Botox is a trusted and approved treatment that temporarily improves the appearance of moderate to severe frown lines, crow’s feet, and forehead lines in adults.</p>
            </div>
            <div className="grid md:grid-cols-3 gap-8 text-center">
                <div className="bg-white p-8 rounded-lg shadow-lg transform hover:-translate-y-2 transition-transform duration-300">
                     {/*
                        This image would be generated by Nano Banana with a prompt:
                        "A simple, flat cartoon-style icon of a smiling face with smooth skin, inside a pink circle. Minimalist and clean."
                    */}
                    <img src="https://picsum.photos/seed/icon1/100/100" alt="Reduce Wrinkles" className="mx-auto h-20 w-20 rounded-full mb-4"/>
                    <h3 className="text-xl font-semibold text-gray-800 mb-2">Reduce Wrinkles</h3>
                    <p className="text-gray-600">Smooth out fine lines and wrinkles for a more youthful, refreshed appearance.</p>
                </div>
                <div className="bg-white p-8 rounded-lg shadow-lg transform hover:-translate-y-2 transition-transform duration-300">
                     {/*
                        This image would be generated by Nano Banana with a prompt:
                        "A simple, flat cartoon-style icon of a calendar with a checkmark, inside a pink circle. Minimalist and clean."
                    */}
                    <img src="https://picsum.photos/seed/icon2/100/100" alt="Quick & Easy" className="mx-auto h-20 w-20 rounded-full mb-4"/>
                    <h3 className="text-xl font-semibold text-gray-800 mb-2">Quick & Easy</h3>
                    <p className="text-gray-600">Treatments are fast, typically lasting only 15 minutes</p>
                </div>
                <div className="bg-white p-8 rounded-lg shadow-lg transform hover:-translate-y-2 transition-transform duration-300">
                    {/*
                        This image would be generated by Nano Banana with a prompt:
                        "A simple, flat cartoon-style icon of a person confidently looking in a mirror, inside a pink circle. Minimalist and clean."
                    */}
                    <img src="https://picsum.photos/seed/icon3/100/100" alt="Natural Results" className="mx-auto h-20 w-20 rounded-full mb-4"/>
                    <h3 className="text-xl font-semibold text-gray-800 mb-2">Natural Results</h3>
                    <p className="text-gray-600">Look like you, only with less noticeable facial lines for a subtle enhancement.</p>
                </div>
            </div>
        </div>
    </section>
);


const Location = () => (
  <section id="location" className="py-20 bg-white">
    <div className="container mx-auto px-6">
      <div className="text-center mb-12">
        <h2 className="text-4xl font-bold text-gray-800">Visit Us</h2>
        <p className="text-gray-600 mt-4">We are conveniently located inside the Pitt River Medical Centre.</p>
      </div>
      <div className="grid md:grid-cols-2 gap-12 items-center">
        <div>
          <h3 className="text-2xl font-semibold text-gray-800 mb-4">Our Address</h3>
          <address className="not-italic">
            <p className="text-lg text-gray-600 mb-2 font-medium">Pitt River Medical Centre</p>
            <p className="text-lg text-gray-600">105-19070 Lougheed Hwy.<br />Pitt Meadows, BC, Canada, V3Y 2M6</p>
          </address>
          <p className="text-lg text-gray-600 mt-4">
            <strong>Phone:</strong> <a href="tel:604-459-9454" className="text-pink-600 hover:underline">(604) 459-9454</a>
          </p>
        </div>
        <div className="rounded-lg shadow-xl overflow-hidden h-96">
          <iframe
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2602.810565814234!2d-122.69335668431086!3d49.2801459793311!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x5485d4757519102b%3A0x89b6af651543883a!2sPitt%20River%20Medical%20Centre!5e0!3m2!1sen!2sca!4v1684357218519!5m2!1sen!2sca"
            width="100%"
            height="100%"
            style={{ border: 0 }}
            allowFullScreen={true}
            loading="lazy"
            referrerPolicy="no-referrer-when-downgrade"
            title="Location of Pavillion Medical at Pitt River Medical Centre"
          ></iframe>
        </div>
      </div>
    </div>
  </section>
);

const Footer = () => (
    <footer className="bg-gray-800 text-white py-8">
        <div className="container mx-auto px-6 text-center">
            <p>&copy; {new Date().getFullYear()} Pavillion Medical. All rights reserved.</p>
            <p className="mt-2">
                Ready to book? <a href="http://calendar.app.google/NSVqrYKdL8SCCtem8" target="_blank" rel="noopener noreferrer" className="text-pink-400 hover:underline font-bold">Book your appointment today!</a>
            </p>
        </div>
    </footer>
);


function App() {
  return (
    <>
      <Header />
      <main>
        <Hero />
        <About />
        <Location />
      </main>
      <Footer />
    </>
  );
}

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(<React.StrictMode><App /></React.StrictMode>);